In [19]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

In [20]:
import numpy as np

dados_x = np.random.rand(4,8)
dados_w = np.random.rand(8,2)

b = tf.compat.v1.random_normal((4,2), 0, 1)

In [21]:
dados_x 

array([[0.42274191, 0.9030164 , 0.88443202, 0.21906941, 0.69979236,
        0.88917345, 0.50707777, 0.4873314 ],
       [0.42602453, 0.6535987 , 0.25438368, 0.03744809, 0.35362219,
        0.36421157, 0.02038412, 0.00532847],
       [0.48997224, 0.68764763, 0.72621209, 0.43105688, 0.55372155,
        0.54261073, 0.2851798 , 0.20182252],
       [0.60428743, 0.71751442, 0.3973065 , 0.18809594, 0.24896135,
        0.39246703, 0.93321317, 0.949598  ]])

In [22]:
dados_w 

array([[0.17339808, 0.73520329],
       [0.38271336, 0.72053691],
       [0.09626372, 0.9505132 ],
       [0.519634  , 0.3865556 ],
       [0.692077  , 0.73751573],
       [0.3381137 , 0.1849736 ],
       [0.54299264, 0.50752392],
       [0.09062882, 0.26188432]])

In [23]:
b

<tf.Tensor 'random_normal_1:0' shape=(4, 2) dtype=float32>

In [26]:
x = tf.compat.v1.placeholder(tf.float32, shape = (4,8))
w = tf.compat.v1.placeholder(tf.float32, shape = (8,2))

operacao = tf.matmul(x, w) +b

In [27]:
operacao

<tf.Tensor 'add:0' shape=(4, 2) dtype=float32>

In [28]:
maximo =  tf.reduce_max(operacao)

In [29]:
maximo 

<tf.Tensor 'Max:0' shape=() dtype=float32>

In [30]:
with tf.compat.v1.Session() as sess:
    saida1 = sess.run(operacao, feed_dict={ x: dados_x, w: dados_w})
    saida2 = sess.run(maximo,feed_dict={ x: dados_x, w: dados_w})

In [31]:
saida1 

array([[2.9398866, 2.448795 ],
       [2.3000307, 1.1578636],
       [2.152633 , 2.5694406],
       [2.0004296, 4.8667364]], dtype=float32)

In [32]:
saida2 

4.479726

In [34]:
import numpy as np

x1 = np.random.randn(4,8)  
w1 = np.random.randn(8,2)  

x2 = np.random.randn(4,8)  
w2 = np.random.randn(8,2)

x3 = np.random.randn(10,3)  
w3 = np.random.randn(3,1)

x4 = np.random.randn(4,8)  
w4 = np.random.randn(8,2)

x5 = np.random.randn(4,8)  
w5 = np.random.randn(8,2)

lista_x = [x1, x2, x3, x4, x5]
lista_w = [w1, w2, w3, w4, w5]
lista_saida = []

b = tf.compat.v1.random_normal((4,2),0,1)   # cria matriz (tensor) de 4 linhas e 2 colunas com números aleatórios

x = tf.compat.v1.placeholder(tf.float32, shape=(None, None))
w = tf.compat.v1.placeholder(tf.float32, shape=(None, None))
operacao = tf.matmul(x, w)

maximo = tf.reduce_max(operacao) # encontra o maior valor da matriz operacao

with tf.compat.v1.Session() as sess:
    for i in range(5):
        saida = sess.run(maximo, feed_dict={x: lista_x[i], w: lista_w[i]})
        lista_saida.append(saida)
print(lista_saida)

[4.7039742, 2.0571682, 2.8754506, 3.0911705, 2.7878373]
